version: '3.8'
services:
  web:
    image: busybox
    tty: true # Allocates a pseudo-TTY to keep a container running.
    extra_hosts:
    - host.docker.internal:host-gateway
    
  db:
    image: busybox
    tty: true
    ports:
    - 5000:5001
    networks:
    - my_test_bridge
    
networks:
  my_test_bridge:
    driver: bridge
